variables:
  # This is a place for you to define variables you can use
  # later in the script by referring to the variable like so:
  #   ${EXAMPLE_VARIABLE}
  FILE_PATH: "/users/grad/jmakwana/AdvSDC/CSCI5308builds"
  
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  tags:
    - ugrad
  artifacts:
    paths:
      - app/build/outputs
  script:
    - echo Building...
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo testing...
    - mvn test
    
deploy:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - mvn package
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"

after_script:
  - echo "End CI and CD!"