variables:
  # This is a place for you to define variables you can use
  # later in the script by referring to the variable like so:
  #   ${EXAMPLE_VARIABLE}
  FILE_PATH: "/users/grad/jmakwana/AdvSDC/CSCI5308builds"
  
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  tags:
    - ugrad
  artifacts:
    paths:
      - app/build/outputs
  script:
    - echo "Building..."
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "Running Test Cases..."
    - mvn test
    
deploy_test:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "DB_NAME=${DB_NAME}" >> config.properties
    - echo "DB_USER_NAME=${DB_USER_NAME}" >> config.properties
    - echo "DB_PASSWORD=${DB_PASSWORD}" >> config.properties
    - cat config.properties
    - echo "Packaging application..."
    - mvn package
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - echo "Compressing package..."
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target config.properties
    - echo "Deploying to test server..."
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - echo "Successfully Deployed on Test Server!"
  environment:
    name: DEVINT
  only:
    - developCICD
    
deploy_prod:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - echo "DB_NAME=${DB_NAME}" >> config.properties
    - echo "DB_USER_NAME=${DB_USER_NAME}" >> config.properties
    - echo "DB_PASSWORD=${DB_PASSWORD}" >> config.properties
    - cat config.properties
    - echo "Packaging application..."
    - mvn package
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - echo "Compressing package..."
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target config.properties
    - echo "Deploying to production server..."
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - echo "Successfully Deployed on Production Server!"
  environment:
    name: TEST
  only:
    - develop
    
after_script:
  - echo "End CI and CD!!"