stages:
  - build
  - test
  
build:
  stage: build
  tags:
    - ugrad
  script:
    - echo Building...
    - mvn compile

test:
  stage: test
  tags:
    - ugrad
  script:
    - echo testing...
    - mvn clean test

after_script:
  - echo "End CI"